version: '3'

# Networks Setup
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

# All the Containers
services:
  # Ghost
  ghost:
    build:
      context: ./ghost
    environment:
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      storage__active: s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      GHOST_STORAGE_ADAPTER_S3_ENDPOINT: ${GHOST_STORAGE_ADAPTER_S3_ENDPOINT}
      GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET: ${GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET}
      GHOST_STORAGE_ADAPTER_S3_PATH_PREFIX: ${GHOST_STORAGE_ADAPTER_S3_PATH_PREFIX}
      GHOST_STORAGE_ADAPTER_S3_ASSET_HOST: ${GHOST_STORAGE_ADAPTER_S3_ASSET_HOST}
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  # MySQL Server
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=5.7.24
    environment:
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/log/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - backend
